apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    synthetic.mom.openshift.io/controller-instance-name: TODO-staticResourceController
  creationTimestamp: null
  labels:
    app: oauth-openshift
  name: oauth-openshift
  namespace: openshift-authentication
