apiVersion: operator.openshift.io/v1
kind: Authentication
metadata:
  annotations:
    operator.openshift.io/controller-name: TODO-deploymentController
  name: cluster
status:
  conditions:
  - lastTransitionTime: "2024-10-14T22:38:20Z"
    reason: PreconditionNotFulfilled
    status: "False"
    type: OAuthServerDeploymentAvailable
  - lastTransitionTime: "2024-10-14T22:38:20Z"
    message: |
      waiting for the oauth-openshift route to appear: route.route.openshift.io "oauth-openshift" not found
    reason: PreconditionNotFulfilled
    status: "True"
    type: OAuthServerDeploymentDegraded
  - lastTransitionTime: "2024-10-14T22:38:20Z"
    reason: PreconditionNotFulfilled
    status: "False"
    type: OAuthServerDeploymentProgressing
  - lastTransitionTime: "2024-10-14T22:38:20Z"
    message: |
      waiting for the oauth-openshift route to appear: route.route.openshift.io "oauth-openshift" not found
    reason: PreconditionNotFulfilled
    status: "True"
    type: OAuthServerWorkloadDegraded
