apiVersion: operator.openshift.io/v1
kind: Authentication
metadata:
  annotations:
    synthetic.mom.openshift.io/controller-instance-name: TODO-other-configObserver
  name: cluster
status:
  conditions:
  - lastTransitionTime: "2024-10-14T22:38:20Z"
    message: |-
      oauth.config.openshift.io "cluster" not found
      endpoints/host-etcd-2 in the openshift-etcd namespace: not found
      configmap openshift-etcd/etcd-endpoints not found, and fallback observer failed
    reason: Error
    status: "True"
    type: OAuthAPIServerConfigObservationDegraded
