apiVersion: operator.openshift.io/v1
kind: Authentication
metadata:
  name: cluster
status:
  conditions:
  - lastTransitionTime: "2024-10-14T22:38:20Z"
    message: configmap "audit" not found
    reason: ContentCreationError
    status: "True"
    type: RevisionControllerDegraded
  latestAvailableRevision: 0
