apiVersion: v1
count: 1
eventTime: null
firstTimestamp: "2024-10-29T15:44:30Z"
involvedObject:
  kind: Deployment
  name: authentication-operator
  namespace: openshift-authentication-operator
kind: Event
lastTimestamp: "2024-10-29T15:44:30Z"
message: 'No valid client certificate for OpenShiftAuthenticatorCertRequester is found:
  unable to parse certificate: data does not contain any valid RSA or ECDSA certificates'
metadata:
  creationTimestamp: null
  name: authentication-operator.1802f6e4f04c905b
  namespace: openshift-authentication-operator
reason: NoValidCertificateFound
reportingComponent: ""
reportingInstance: ""
source:
  component: cluster-authentication-operator-run-once-sync-context
type: Normal
