apiVersion: v1
count: 1
eventTime: null
firstTimestamp: "2024-10-14T22:38:20Z"
involvedObject:
  kind: Deployment
  name: authentication-operator
  namespace: openshift-authentication-operator
kind: Event
lastTimestamp: "2024-10-14T22:38:20Z"
message: Required endpoints/host-etcd-2 in the openshift-etcd namespace not found.
metadata:
  creationTimestamp: null
  name: authentication-operator.17fe72c59b829800.b8ffb9fd
  namespace: openshift-authentication-operator
reason: ObserveStorageFailed
reportingComponent: ""
reportingInstance: ""
source:
  component: cluster-authentication-operator-run-once-sync-context
type: Warning
