apiVersion: v1
data:
  v4-0-config-system-session: eyJraW5kIjoiU2Vzc2lvblNlY3JldHMiLCJhcGlWZXJzaW9uIjoib3BlcmF0b3J2MWNsaWVudCIsInNlY3JldHMiOlt7ImF1dGhlbnRpY2F0aW9uIjoiZXlFUDNvR21XNnNEdW5JWlV2aHVabFJXV25GdlpkQ2RhYXJCZGl0MEJ2b1FKOVp2aW8xcHdNMUdDNXF6RTY2NyIsImVuY3J5cHRpb24iOiJmSDNqeF9CR0J0alBZQW9HU011M3RJbVpLX29aRmdWeiJ9XX0=
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    app: oauth-openshift
  name: v4-0-config-system-session
  namespace: openshift-authentication
